"""
Helper to load .pt sample data files generated by sample-data/generate_samples.py.

Usage:
    from tests.helpers.load_sample_data import list_samples, load_sample

    for info in list_samples():
        sample = load_sample(info['path'])
        q, c_kv, k_rope = sample['q'], sample['c_kv'], sample['k_rope']
"""

import torch
from pathlib import Path

SAMPLE_DIR = Path(__file__).resolve().parent.parent.parent / 'sample-data'


def list_samples(model=None, mode=None, source=None):
    """List available sample data files.

    Args:
        model: Filter by model name (e.g., 'kimi_k2.5', 'deepseek_v32')
        mode: Filter by mode ('decode' for s_q=1, 'prefill' for s_q>1)
        source: Filter by data source ('random', 'tokenized', or None for all)

    Returns:
        List of dicts with keys: path, model, suffix, s_kv, s_q, tokenized
    """
    if not SAMPLE_DIR.exists():
        return []

    results = []
    for pt_file in sorted(SAMPLE_DIR.glob('*.pt')):
        name = pt_file.stem
        # Parse: {model}_{suffix} where suffix is like s256, tok_s1024, fwd_s1024
        # Models have underscores in name (kimi_k2.5, deepseek_v32)
        for prefix in ['kimi_k2.5', 'deepseek_v32']:
            if name.startswith(prefix + '_'):
                suffix = name[len(prefix) + 1:]

                # Strip mode prefixes: fwd_ and/or tok_
                is_fwd = suffix.startswith('fwd_')
                if is_fwd:
                    suffix_rest = suffix[4:]
                else:
                    suffix_rest = suffix
                is_tok = suffix_rest.startswith('tok_')
                core_suffix = suffix_rest[4:] if is_tok else suffix_rest
                is_prefill = core_suffix.startswith('prefill_')

                if model and prefix != model:
                    continue
                if mode == 'decode' and is_prefill:
                    continue
                if mode == 'prefill' and not is_prefill:
                    continue
                if source == 'random' and (is_tok or is_fwd):
                    continue
                if source == 'tokenized' and not is_tok and not is_fwd:
                    continue
                if source == 'forward' and not is_fwd:
                    continue

                # Parse s_kv from core suffix (supports s256, s32k, etc.)
                s_part = core_suffix.replace('prefill_', '')
                if s_part.endswith('k'):
                    s_kv = int(s_part.lstrip('s').rstrip('k')) * 1024
                else:
                    s_kv = int(s_part.lstrip('s'))
                s_q = 128 if is_prefill else 1

                results.append({
                    'path': pt_file,
                    'model': prefix,
                    'suffix': name[len(prefix) + 1:],
                    's_kv': s_kv,
                    's_q': s_q,
                    'tokenized': is_tok or is_fwd,
                    'forward': is_fwd,
                })
                break

    return results


def load_sample(path):
    """Load a .pt sample file and return its contents.

    Returns dict with keys: q, c_kv, k_rope, model, s_kv, s_q
    All tensors are in BF16 as stored.
    """
    return torch.load(str(path), map_location='cpu', weights_only=True)


def has_samples():
    """Check if any sample data files exist."""
    return len(list_samples()) > 0
